---
title: Comando básicos R
author: Lucas Jordão
output:
  html_fragment: default
date: '2019-05-10'
slug: comando-basicos-r
categories: []
tags: []
image:
  caption: ''
  focal_point: ''
---

(provisório)

## Operadores simples e funções matemáticas
```{r}
2+3 # + = adição
7-5 # * = subtração
4*5 # * = multiplicação
6/3 # / = divisão
9%%2 # resto da divisão
9%/%2 # resultado inteiro da divisão
4^4 # ^ = potência

sqrt(81) # raiz quadrada
exp(12) # função exponencial
log(3) # logaritmo natural de 3
log(3, 10) # logaritmo de 3 na base 10
abs(-6.45) # retorna o valor absoluto
factorial(5) # fatorial de 5 = 5x4x3x2x1
gamma(10) # função gama
lgamma(10) # log natural gama
round(10.342545, digits=2) # arredondamento de números decimais
```

## Sequências
```{r}
seq(1:20) # Gera uma sequência de 1 a 20
seq(1, 20, 2) # Gera uma sequência de 1 a 20, de 2 em 2
seq(from=5, by=-1, along=1:20) # Gera uma sequência iniciando em 5 e subtraindo -1, 20 vezes
```

## Repetições
```{r}
rep(5.3, 17) # Repete o valor 5.3, 17 vezes
rep(1:6, rep(3)) # Repete a sequência 1 a 6, 3 vezes
```

## Constantes do R
```{r}
LETTERS
letters
month.abb
month.name
pi
```

## Ordenando valores
```{r}
sort(letters)
sort(letters, decreasing=TRUE)
```

---

## TIPOS DE DADOS

### numerical


### character
```{r}
x<-"R"
x
```

### valores lógicos
```{r}
TRUE
FALSE
TRUE | FALSE # logical 'ou'= |
TRUE & FALSE # logical 'e' = &
!TRUE # logical 'não' = !
```

### factor

(continua...)