---
title: Hello world, speaking animals, and some fortunes
author: Lucas Jordão
output:
  html_fragment: default
date: '2019-05-04'
slug: hello-world-animals-and-some-fortunes
categories: []
tags: []
image:
  caption: ''
  focal_point: ''
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> Hi there! I'm glad you here!  :smile:  
> :mega: This is my first post!  
> :sparkles: It's fantastic :sparkles: to use R programming languange in HTML.

---

> Take a :eyes: in these two packages for newbies in <i class="fab fa-r-project" style="color:blue"></i>...

```{r packages, include=FALSE}
library(cowsay)
library(emo)
```

* [Cowsay package](https://cran.r-project.org/web/packages/cowsay/vignettes/cowsay_tutorial.html) - Speaking animals :cow: :monkey:
```{r cowsay, echo=TRUE, warning=FALSE}
say("Hello world!", "cow")
say("Hello you!", "monkey")
```

* [Fortunes package](https://cran.r-project.org/web/packages/fortunes/vignettes/fortunes.pdf) - Collected Wisdom :bulb: in <i class="fab fa-r-project" style="color:blue">
```{r echo=FALSE, warning=FALSE}
library(fortunes)
fortune(6)

fortune(68)

fortune(92)

fortune(192)

fortune(326)
```